[nameless]
version = "2025.01.24"
description = "Just a normal bot."
support_server = ""

[command]
prefixes = ["n."]

[[wavelinks]]
name = "default"
uri = "http://localhost:2333"
password = "youshallnotpass"
auto_start = true
auto_update = true
