[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO
log_cli_format = %(levelname)s [%(name)s] %(message)s

filterwarnings = ignore::DeprecationWarning
