"""Added radio start time record

Revision ID: 5e0f3fab617e
Revises: 
Create Date: 2022-04-12 18:13:37.848474

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e0f3fab617e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Guilds", sa.Column("RadioStartTime", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Guilds", "RadioStartTime")
    # ### end Alembic commands ###
