"""Add more guild setting fields

Revision ID: 7075bbb95141
Revises: d413fb7c83d4
Create Date: 2023-01-17 21:52:44.765561

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "7075bbb95141"
down_revision = "d413fb7c83d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Guilds", sa.Column("IsBotGreetingEnabled", sa.Boolean(), nullable=True))
    op.add_column("Guilds", sa.Column("IsDmPreferred", sa.Boolean(), nullable=True))
    op.add_column("Guilds", sa.Column("IsTimeoutPreferred", sa.Boolean(), nullable=True))
    op.add_column("Guilds", sa.Column("MaxWarnCount", sa.BigInteger(), nullable=True))
    op.add_column("Guilds", sa.Column("MuteRoleId", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Guilds", "IsBotGreetingEnabled")
    op.drop_column("Guilds", "IsDmPreferred")
    op.drop_column("Guilds", "IsTimeoutPreferred")
    op.drop_column("Guilds", "MaxWarnCount")
    op.drop_column("Guilds", "MuteRoleId")
    # ### end Alembic commands ###
