"""Remove moderation stuffs

Revision ID: 951b4b2270fa
Revises: e412b029eee9
Create Date: 2024-03-10 21:06:12.799622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b4b2270fa'
down_revision = 'e412b029eee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Guilds', 'MaxWarnCount')
    op.drop_column('Guilds', 'IsTimeoutPreferred')
    op.drop_column('Guilds', 'MuteRoleId')
    op.drop_column('Guilds', 'MuteTimeoutInterval')
    op.drop_column('Users', 'WarnCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('WarnCount', sa.SMALLINT(), nullable=True))
    op.add_column('Guilds', sa.Column('MuteTimeoutInterval', sa.DATETIME(), nullable=True))
    op.add_column('Guilds', sa.Column('MuteRoleId', sa.BIGINT(), nullable=True))
    op.add_column('Guilds', sa.Column('IsTimeoutPreferred', sa.BOOLEAN(), nullable=True))
    op.add_column('Guilds', sa.Column('MaxWarnCount', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###
