"""Remove moderation stuffs

Revision ID: 951b4b2270fa
Revises: e412b029eee9
Create Date: 2024-03-10 21:06:12.799622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b4b2270fa'
down_revision = 'e412b029eee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Guilds', 'IsWelcomeEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Guilds', 'IsGoodbyeEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Guilds', 'IsBotGreetingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Guilds', 'IsDmPreferred',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Guilds', 'WelcomeChannelId',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('Guilds', 'GoodbyeChannelId',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('Guilds', 'WelcomeMessage',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Guilds', 'GoodbyeMessage',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Guilds', 'AudioRoleId',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('Guilds', 'RadioStartTime',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('Guilds', 'VoiceRoomChannelId',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('Guilds', 'MaxWarnCount')
    op.drop_column('Guilds', 'IsTimeoutPreferred')
    op.drop_column('Guilds', 'MuteRoleId')
    op.drop_column('Guilds', 'MuteTimeoutInterval')
    op.alter_column('Users', 'OsuUsername',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Users', 'OsuMode',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('Users', 'WarnCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('WarnCount', sa.SMALLINT(), nullable=True))
    op.alter_column('Users', 'OsuMode',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Users', 'OsuUsername',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('Guilds', sa.Column('MuteTimeoutInterval', sa.DATETIME(), nullable=True))
    op.add_column('Guilds', sa.Column('MuteRoleId', sa.BIGINT(), nullable=True))
    op.add_column('Guilds', sa.Column('IsTimeoutPreferred', sa.BOOLEAN(), nullable=True))
    op.add_column('Guilds', sa.Column('MaxWarnCount', sa.BIGINT(), nullable=True))
    op.alter_column('Guilds', 'VoiceRoomChannelId',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Guilds', 'RadioStartTime',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('Guilds', 'AudioRoleId',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('Guilds', 'GoodbyeMessage',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Guilds', 'WelcomeMessage',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Guilds', 'GoodbyeChannelId',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('Guilds', 'WelcomeChannelId',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('Guilds', 'IsDmPreferred',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Guilds', 'IsBotGreetingEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Guilds', 'IsGoodbyeEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Guilds', 'IsWelcomeEnabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
