"""Add audio role

Revision ID: e412b029eee9
Revises: b3423eb03119
Create Date: 2024-02-15 20:26:15.881513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e412b029eee9'
down_revision = 'b3423eb03119'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Guilds', sa.Column('AudioRoleId', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Guilds', 'AudioRoleId')
    # ### end Alembic commands ###
