# pyright: reportUninitializedInstanceVariable=false
# ruff: noqa: N815, N818

# literally too lazy to setup .pyi stubs
# so just defining the types here for type checking purposes
# should we use `if TYPE_CHECKING` also?

from typing import Any


class Object:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def json(self) -> str: ...


class JSException(Exception): ...


class StackOverflow(JSException): ...


class Context:
    globalThis: Object

    def eval(self, code: str, *args: Any, **kwargs: Any) -> Any: ...
    def module(self, code: str, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, name: str) -> Any: ...
    def set(self, name: str, value: Any) -> None: ...
    def parse_json(self, s: str) -> Any: ...
    def add_callable(self, global_name: str, fn: Any) -> None: ...
    def set_memory_limit(self, limit: int) -> None: ...
    def set_time_limit(self, limit: float) -> None: ...
    def set_max_stack_size(self, limit: int) -> None: ...
    def memory(self) -> dict[str, Any]: ...
    def gc(self) -> None: ...
    def execute_pending_job(self) -> bool: ...
